name: audiogen

dependencies:
  - python=3.12
  - pip:
    - ipykernel
    - ipython
    - isort
    - jupyter
    - jupyterlab
    - matplotlib
    - numpy
    - pandas
    - pylint
    - pytest
    - scikit-learn
    - scipy
    - toml
    - tqdm
    - yapf
    - torch
    - librosa
